### ISSUE TITLE
Error when run npm start: Class constructor ServeCommand cannot be invoked without 'new'

### ISSUE THREAD

**Issue by jiyuujin** [nekohack-oss/webpack5-preact#1]
```
[webpack-cli] Promise rejection: TypeError: Class constructor ServeCommand cannot be invoked without 'new'
[webpack-cli] TypeError: Class constructor ServeCommand cannot be invoked without 'new'
    at Object.run (/Users/yuukit/project/webpack5-preact/node_modules/webpack-cli/lib/commands/resolveCommand.js:35:47)
    at Command.<anonymous> (/Users/yuukit/project/webpack5-preact/node_modules/webpack-cli/lib/utils/arg-parser.js:31:68)
    at Command.listener [as _actionHandler] (/Users/yuukit/project/webpack5-preact/node_modules/webpack-cli/node_modules/commander/index.js:426:31)
    at Command._parseCommand (/Users/yuukit/project/webpack5-preact/node_modules/webpack-cli/node_modules/commander/index.js:1002:14)
    at Command._dispatchSubcommand (/Users/yuukit/project/webpack5-preact/node_modules/webpack-cli/node_modules/commander/index.js:953:18)
    at Command._parseCommand (/Users/yuukit/project/webpack5-preact/node_modules/webpack-cli/node_modules/commander/index.js:970:12)
    at Command.parse (/Users/yuukit/project/webpack5-preact/node_modules/webpack-cli/node_modules/commander/index.js:801:10)
    at argParser (/Users/yuukit/project/webpack5-preact/node_modules/webpack-cli/lib/utils/arg-parser.js:121:27)
    at runCLI (/Users/yuukit/project/webpack5-preact/node_modules/webpack-cli/lib/bootstrap.js:20:24)
    at Object.<anonymous> (/Users/yuukit/project/webpack5-preact/node_modules/webpack-cli/bin/cli.js:19:5)
✨  Done in 0.54s.
```

**Comment by jiyuujin** [comment]
https://github.com/webpack/webpack-cli/issues/2272#issuecomment-752048270
